/**
 * Shape of public/semantic-search/manifest.json, generated by
 * scripts/generate-embeddings.mts and fetched by the browser at runtime.
 * Treated as untrusted input on the client (same policy as any other
 * fetched JSON) — parseSemanticManifest validates before anything trusts it.
 */
export interface SemanticManifest {
  readonly modelId: string;
  readonly dimensions: number;
  /** Deterministic hash of the asset id set the embeddings were generated from — see catalog-version.ts. */
  readonly catalogVersion: string;
  readonly generatedAt: string;
  readonly count: number;
  /** Asset ids in the exact row order they appear in embeddings.bin. */
  readonly assetIds: readonly string[];
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isStringArray(value: unknown): value is readonly string[] {
  return Array.isArray(value) && value.every((entry) => typeof entry === "string");
}

/**
 * Validates a fetched manifest.json. Returns null (never throws) for
 * anything malformed or internally inconsistent, so the caller can fall
 * back to keyword search instead of crashing on a corrupt/mismatched
 * artifact.
 */
export function parseSemanticManifest(value: unknown): SemanticManifest | null {
  if (!isRecord(value)) return null;

  const { modelId, dimensions, catalogVersion, generatedAt, count, assetIds } = value;

  if (typeof modelId !== "string" || modelId.trim() === "") return null;
  if (typeof dimensions !== "number" || !Number.isFinite(dimensions) || dimensions <= 0) return null;
  if (typeof catalogVersion !== "string" || catalogVersion.trim() === "") return null;
  if (typeof generatedAt !== "string" || generatedAt.trim() === "") return null;
  if (typeof count !== "number" || !Number.isInteger(count) || count < 0) return null;
  if (!isStringArray(assetIds)) return null;
  if (assetIds.length !== count) return null;

  return { modelId, dimensions, catalogVersion, generatedAt, count, assetIds };
}
